export enum SlashType {
  UNKNOWN = 0,
  UNAVAILABILITY_TIER_1 = 1,
  UNAVAILABILITY_TIER_2 = 2,
  DOUBLE_SIGNING = 3,
  BRIDGE_VOTING = 4,
  BRIDGE_OPERATOR_MISSING_VOTE_TIER_1 = 5,
  BRIDGE_OPERATOR_MISSING_VOTE_TIER_2 = 6,
  UNAVAILABILITY_TIER_3 = 7,
}
