// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

enum Roles {
  ADMIN,
  GOVERNOR,
  COINBASE,
  CANDIDATE_ADMIN,
  EMERGENCY_PAUSER,
  WITHDRAWAL_MIGRATOR,
  BRIDGE,
  BRIDGE_OPERATOR,
  BRIDGE_TRACKING,
  MAINTENANCE,
  GOVERNANCE_ADMIN,
  SLASH_INDICATOR,
  STAKING,
  STAKING_VESTING,
  VALIDATOR,
  VALIDATOR_CANDIDATE,
  BLOCK_PRODUCER,
  RONIN_TRUSTED_ORGANIZATION
}
