// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

enum Role {
  ADMIN, // 0
  GOVERNOR, // 1
  COINBASE, // 2
  CANDIDATE_ADMIN, // 3
  EMERGENCY_PAUSER, // 4
  WITHDRAWAL_MIGRATOR, // 5
  BRIDGE_CONTRACT, // 6
  BRIDGE_OPERATOR, // 7
  BRIDGE_TRACKING_CONTRACT, // 8
  MAINTENANCE_CONTRACT, // 9
  GOVERNANCE_ADMIN_CONTRACT, // 10
  SLASH_INDICATOR_CONTRACT, // 11
  STAKING_CONTRACT, // 12
  STAKING_VESTING_CONTRACT, // 13
  VALIDATOR_CONTRACT, // 14
  VALIDATOR_CANDIDATE, // 15
  BLOCK_PRODUCER, // 16
  RONIN_TRUSTED_ORGANIZATION_CONTRACT // 17
}
