// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

enum Roles {
  UNKNOWN, // 0
  ADMIN, // 1
  GOVERNOR, // 2
  COINBASE, // 3
  CANDIDATE_ADMIN, // 4
  EMERGENCY_PAUSER, // 5
  WITHDRAWAL_MIGRATOR, // 6
  BRIDGE_CONTRACT, // 7
  BRIDGE_OPERATOR, // 8
  BRIDGE_TRACKING_CONTRACT, // 9
  MAINTENANCE_CONTRACT, // 10
  GOVERNANCE_ADMIN_CONTRACT, // 11
  SLASH_INDICATOR_CONTRACT, // 12
  STAKING_CONTRACT, // 13
  STAKING_VESTING_CONTRACT, // 14
  VALIDATOR_CONTRACT, // 15
  VALIDATOR_CANDIDATE, // 16
  BLOCK_PRODUCER, // 17
  RONIN_TRUSTED_ORGANIZATION_CONTRACT // 18
}
