#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

set -ex

yarn lint-staged
yarn clean
yarn compile
yarn plugin:storage-layout --override true
git add logs/storage_layout.log
git add logs/contract_code_sizes.log