name: Run tests
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions:
  packages: read

jobs:
  nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 #v3.0.2

      - name: 'Setup Node'
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 #v3.4.1
        with:
          node-version: v14.18.1

      - name: Github private package token in npmrc
        run: |
          echo "@axieinfinity:registry=https://npm.pkg.github.com/" >> .npmrc

      - name: 'Run install'
        uses: borales/actions-yarn@97ba8bebfe5b549bb7999261698a52a81fd62f1b #v4.2.0
        with:
          cmd: install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Run Compile'
        uses: borales/actions-yarn@97ba8bebfe5b549bb7999261698a52a81fd62f1b #v4.2.0
        with:
          cmd: compile

      - name: 'Run Test'
        uses: borales/actions-yarn@97ba8bebfe5b549bb7999261698a52a81fd62f1b #v4.2.0
        with:
          cmd: test
