name: Run tests
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    uses: axieinfinity/workflows-samples/.github/workflows/testing-node.yml@main
    with:
      node_version: v14.18.1
